// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file auth.proto (package com.qapp.auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GoogleLoginRequest, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse } from "./auth_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service com.qapp.auth.AuthService
 */
export const AuthService = {
  typeName: "com.qapp.auth.AuthService",
  methods: {
    /**
     * @generated from rpc com.qapp.auth.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.qapp.auth.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.qapp.auth.AuthService.GoogleOAuthLogin
     */
    googleOAuthLogin: {
      name: "GoogleOAuthLogin",
      I: GoogleLoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

